version: "3"
services:
  greenvironment:
    build: .
    user: "root"
    working_dir: /home/node/green
    environment:
      - NODE_ENV=production
    ports:
      - "8080:8080"
    command: "npm start"
