version: "2"
services:
  greenvironment:
    build:
      context: .
      dockerfile: ./Dockerfile
    user: "node"
    working_dir: /home/node/green
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/green
    expose:
      - "8080"
    command: "npm start"
