# database connection info
database:
  connectionUri: "sqlite://:memory:"

# http server configuration
server:
  port: 8080
  cors: false

session:
  secret: REPLACE WITH SAFE RANDOM GENERATED SECRET
  cookieMaxAge: 604800000‬ # 7 days

markdown:
  plugins:
    - 'markdown-it-emoji'

logging:
  level: info
